dist: trusty
sudo: false
language: generic
before_install:
  - wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
    --output-document miniforge.sh
  - bash miniforge.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all
install:
  - conda env create --quiet --file environment.yml
  - conda activate hetmech
  - conda list
script:
  - jupyter nbconvert --to=script --stdout *.ipynb |
    flake8 --exit-zero --show-source -
